// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnjzagcjptgsaapypilo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuanphZ2NqcHRnc2FhcHlwaWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5Njg2NTEsImV4cCI6MjA2NzU0NDY1MX0.r3qrKrUqVK402p3vdpiYRk2LRbcpPgQMW3LSXbVXIyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});